# Logistic Regression Parameters
LogisticRegression:
  C: 1.0
  max_iter: 1000
  penalty: 'l2'
  solver: 'liblinear'
  class_weight: 'balanced'

# Random Forest Classifier Parameters
RandomForestClassifier:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: 'sqrt'
  class_weight: 'balanced'
  
# LightGBM Classifier Parameters
LGBMClassifier:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 8
  num_leaves: 31
  min_child_samples: 20
  class_weight: 'balanced'
  boosting_type: 'gbdt'
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 5

# SMOTE Parameters
SMOTE:
  k_neighbors: 5
  sampling_strategy: 'auto'